/**
 * The pin (slice 004 `tonight-page`, T001): today's markup of the Today screen, both views, and of
 * Tonight, every state, outside any shell.
 *
 * Captured from the code as it stood before the slice changed either screen (`4e4b76c`), and seen passing
 * there. Outside a notebook page both screens must render exactly this, element for element (SC-009), so
 * Current and every existing screen test are unchanged. A change here is a change to today's interface: it
 * needs its own decision, never a re-capture to make a test pass.
 *
 * Every time of day is interpolated from the same `toLocaleTimeString` call the screens make, so the pin
 * does not depend on the runner's locale; the zone is fixed before any date is made.
 */
declare const process: { env: Record<string, string | undefined> };
process.env.TZ = 'Europe/London';

import { act, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { CheckIn } from '../CheckIn';
import { Reaches } from '../Reaches';
import { installFakeCore, type FakeCore } from './fakeCore';
import {
  evening,
  lateEvening,
  overTimeCases,
  overTimeReader,
  reachesOfTheDay,
  silentReader,
  todayCases,
  tonightCases,
  tonightCore,
} from './tonightCases';

const time = (seconds: number) =>
  new Date(seconds * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
const [t0, t1, t2] = reachesOfTheDay.map((reach) => time(reach.at));

const TODAY: Record<string, string> = {
  looking:
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Today</button><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><p class="text-ink-400">Looking…</p></section></div>',
  'a log, the fallback note':
    `<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Today</button><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Today</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn counts only while it is running. This is what it saw today.</p></section></div>`,
  'a log, a coverage note':
    `<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Today</button><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Today</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn was not running for 2 hours today, so this may not be everything.</p></section></div>`,
  'nothing yet, the fallback note':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Today</button><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Today</h2><p class="reflective mt-4 max-w-prose text-lg text-ink-700">Nothing here for today.</p><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn counts only while it is running. This is what it saw today.</p></section></div>',
  'nothing yet, a coverage note':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Today</button><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Today</h2><p class="reflective mt-4 max-w-prose text-lg text-ink-700">Nothing here for today.</p><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn was not running for 2 hours today, so this may not be everything.</p></section></div>',
  sealed:
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Today</button><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Today</h2><p class="reflective mt-4 max-w-prose text-lg text-ink-700">Cairn cannot open your history just now. Protection is unaffected, and nothing has been lost.</p></section></div>',
};

const OVER_TIME: Record<string, string> = {
  looking:
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><p class="mt-8 text-ink-400">Looking…</p></section></div>',
  'could not read':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><p class="reflective mt-8 max-w-prose text-lg text-ink-700">Cairn could not read your history just now. Protection is unaffected.</p></section></div>',
  sealed:
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><p class="reflective mt-8 max-w-prose text-lg text-ink-700">Cairn cannot open your history just now. Protection is unaffected, and nothing has been lost.</p></section></div>',
  'a list':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><ul class="mt-8 divide-y divide-sand-200"><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-500">9</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 100%;"></div></div></li><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-500">4</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 44%;"></div></div></li><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">shop.example</span><span class="text-sm text-ink-500">1</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 11%;"></div></div></li></ul><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn counts only while it is running. This is what it saw over these days.</p></section></div>',
  'a list, a coverage note':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><p class="reflective mt-8 max-w-prose text-ink-500">Cairn was not running for 3 days in this range, so this may not be everything.</p><ul class="mt-8 divide-y divide-sand-200"><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-500">9</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 100%;"></div></div></li><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-500">4</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 44%;"></div></div></li><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">shop.example</span><span class="text-sm text-ink-500">1</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 11%;"></div></div></li></ul><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn counts only while it is running. This is what it saw over these days.</p></section></div>',
  'a list, one estimate':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><p class="reflective mt-4 max-w-prose text-ink-500">Your own estimate for 1 day is not counted here, because an estimate has no site.</p><ul class="mt-8 divide-y divide-sand-200"><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-500">9</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 100%;"></div></div></li><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-500">4</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 44%;"></div></div></li><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">shop.example</span><span class="text-sm text-ink-500">1</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 11%;"></div></div></li></ul><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn counts only while it is running. This is what it saw over these days.</p></section></div>',
  'a list, a coverage note and several estimates':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><p class="reflective mt-8 max-w-prose text-ink-500">Cairn was not running for 3 days in this range, so this may not be everything.</p><p class="reflective mt-4 max-w-prose text-ink-500">Your own estimates for 3 days are not counted here, because an estimate has no site.</p><ul class="mt-8 divide-y divide-sand-200"><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-500">9</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 100%;"></div></div></li><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-500">4</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 44%;"></div></div></li><li class="py-3"><div class="flex items-baseline justify-between"><span class="text-ink-900">shop.example</span><span class="text-sm text-ink-500">1</span></div><div aria-hidden="true" class="mt-2 h-1.5 rounded-full bg-sand-100"><div data-testid="bar" class="h-1.5 rounded-full bg-moss-500" style="width: 11%;"></div></div></li></ul><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn counts only while it is running. This is what it saw over these days.</p></section></div>',
  'nothing here':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><p class="reflective mt-8 max-w-prose text-lg text-ink-700">Nothing here for these days.</p><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn counts only while it is running. This is what it saw over these days.</p></section></div>',
  'nothing here, a coverage note and several estimates':
    '<div><div class="mb-4 flex gap-2" role="group" aria-label="Which days"><button type="button" aria-pressed="false" class="rounded-full px-4 py-1.5 text-sm text-ink-500 hover:bg-sand-100">Today</button><button type="button" aria-pressed="true" class="rounded-full px-4 py-1.5 text-sm bg-sand-200 text-ink-900">Over time</button></div><section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">From 3 September to 30 September</h2><div class="mt-6 flex flex-wrap gap-6 text-sm text-ink-500"><label class="flex items-center gap-2">From<input type="date" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-03"></label><label class="flex items-center gap-2">To<input type="date" min="2026-09-03" max="2026-09-30" class="rounded-lg border border-sand-300 bg-white/70 px-2 py-1 text-ink-700" value="2026-09-30"></label></div><p class="reflective mt-8 max-w-prose text-ink-500">Cairn was not running for 3 days in this range, so this may not be everything.</p><p class="reflective mt-4 max-w-prose text-ink-500">Your own estimates for 2 days are not counted here, because an estimate has no site.</p><p class="reflective mt-8 max-w-prose text-lg text-ink-700">Nothing here for these days.</p><p class="reflective mt-8 border-t border-sand-200 pt-6 text-ink-500">Cairn counts only while it is running. This is what it saw over these days.</p></section></div>',
};

const TONIGHT: Record<string, string> = {
  looking:
    '<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><p class="text-ink-400">Looking…</p></section>',
  'a load that could not be made':
    '<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><p class="text-ink-400">Cairn could not open today just now. Protection is unaffected.</p></section>',
  'reaches, no coverage note, quotes hidden':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div></section>`,
  'no reaches, no coverage note, quotes hidden':
    '<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><p class="reflective mt-4 max-w-prose text-lg text-ink-700">Nothing here for today.</p><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div></section>',
  'reaches, a coverage note, quotes hidden':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><p class="reflective mt-6 text-ink-500">Cairn was not running for 2 hours today, so this may not be everything.</p><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div></section>`,
  'no reaches, a coverage note, quotes hidden':
    '<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><p class="reflective mt-4 max-w-prose text-lg text-ink-700">Nothing here for today.</p><p class="reflective mt-6 text-ink-500">Cairn was not running for 2 hours today, so this may not be everything.</p><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div></section>',
  'reaches, with a quote':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><figure class="mt-6"><p class="reflective max-w-prose text-lg italic text-ink-500">The path is made by walking.</p></figure><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Hide quotes</button></div></section>`,
  'reaches, quotes shown and none to be had':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Hide quotes</button></div></section>`,
  'reaches, the quotes setting unknown':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p></section>`,
  'an entry written before':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none">A slow morning, a better afternoon.</textarea></label><div class="mt-4 flex items-center gap-4"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div></section>`,
  'an entry kept':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none">Back on the trail.</textarea></label><div class="mt-4 flex items-center gap-4"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700">Kept for today.</p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div></section>`,
  'a refused save':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none">Back on the trail.</textarea></label><div class="mt-4 flex items-center gap-4"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700">The entry was not kept. What you wrote is still here.</p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div></section>`,
  'a refused switch':
    `<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><figure class="mt-6"><p class="reflective max-w-prose text-lg italic text-ink-500">The path is made by walking.</p></figure><ul class="mt-8 divide-y divide-sand-200"><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t0}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">video.example</span><span class="text-sm text-ink-400">${t1}</span></li><li class="flex items-baseline justify-between py-3"><span class="text-ink-900">news.example</span><span class="text-sm text-ink-400">${t2}</span></li></ul><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700">Cairn could not keep that choice.</p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Hide quotes</button></div></section>`,
  'sealed, quotes hidden':
    '<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><p class="reflective mt-4 max-w-prose text-lg text-ink-700">Cairn cannot open your history just now. Protection is unaffected, and nothing has been lost.</p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p></section>',
  'sealed, with a quote':
    '<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Tonight</h2><figure class="mt-6"><p class="reflective max-w-prose text-lg italic text-ink-500">The path is made by walking.</p></figure><p class="reflective mt-4 max-w-prose text-lg text-ink-700">Cairn cannot open your history just now. Protection is unaffected, and nothing has been lost.</p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Hide quotes</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p></section>',
  'a day that ended while open':
    '<section class="settle rounded-2xl border border-sand-200 bg-white/60 p-8 "><h2 class="reflective text-3xl text-ink-900">Wednesday 30 September</h2><p class="reflective mt-4 max-w-prose text-lg text-ink-700">Nothing here for Wednesday 30 September.</p><label class="mt-10 block"><span class="reflective text-xl text-ink-700">How the day went</span><textarea class="reflective mt-3 block min-h-48 w-full rounded-lg border border-sand-200 bg-sand-50 p-4 text-lg leading-relaxed text-ink-900 focus:border-clay-500 focus:outline-none"></textarea></label><div class="mt-4 flex items-center gap-4"><button disabled="" class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-clay-600 text-sand-50 hover:bg-clay-500 disabled:bg-sand-300 disabled:text-ink-400 ">Keep this</button></div><p role="status" aria-live="polite" class="reflective mt-4 max-w-prose text-ink-700"></p><div class="mt-10"><button class="rounded-lg px-5 py-2.5 text-sm font-medium transition-colors duration-200 disabled:cursor-not-allowed bg-transparent text-ink-500 hover:text-ink-900 hover:bg-sand-100 px-0">Show quotes</button></div></section>',
};

describe("Today, the Today view, outside any shell, is today's markup", () => {
  it.each(Object.keys(todayCases))('%s', (name) => {
    const { container } = render(
      <Reaches today={todayCases[name]} read={silentReader} now={evening} />,
    );
    expect(container.innerHTML).toBe(TODAY[name]);
  });

  it('pins every case', () => {
    expect(Object.keys(TODAY).sort()).toEqual(Object.keys(todayCases).sort());
  });
});

describe("Today, the Over time view, outside any shell, is today's markup", () => {
  it.each(Object.keys(overTimeCases))('%s', async (name) => {
    const answer = overTimeCases[name]!;
    const { container } = render(
      <Reaches today={todayCases['nothing yet, the fallback note']} read={overTimeReader(answer)} now={evening} />,
    );
    fireEvent.click(screen.getByRole('button', { name: 'Over time' }));
    if (answer === 'unreadable') {
      await screen.findByText('Cairn could not read your history just now. Protection is unaffected.');
    } else if (answer !== 'looking') {
      await screen.findByText(answer.sealed ?? 'Cairn counts only while it is running. This is what it saw over these days.');
    }
    expect(container.innerHTML).toBe(OVER_TIME[name]);
  });

  it('pins every case', () => {
    expect(Object.keys(OVER_TIME).sort()).toEqual(Object.keys(overTimeCases).sort());
  });
});

describe("Tonight, outside any shell, is today's markup", () => {
  let core: FakeCore | undefined;
  afterEach(() => {
    core?.remove();
    core = undefined;
    vi.useRealTimers();
  });

  /** Lets every answer the fake core has given reach the screen. */
  const settle = () =>
    act(async () => {
      await vi.advanceTimersByTimeAsync(0);
    });

  it.each(Object.keys(tonightCases))('%s', async (name) => {
    const c = tonightCases[name]!;
    vi.useFakeTimers({ toFake: ['Date', 'setTimeout', 'clearTimeout'] });
    vi.setSystemTime(c.endsWhileOpen ? lateEvening() : evening());
    core = installFakeCore(tonightCore(c));

    const { container } = render(<CheckIn />);
    await settle();

    if (c.keep) {
      fireEvent.change(screen.getByRole('textbox'), { target: { value: c.keep.typed } });
      fireEvent.click(screen.getByRole('button', { name: 'Keep this' }));
      await settle();
    }
    if (c.switchRefused) {
      fireEvent.click(screen.getByRole('button', { name: 'Hide quotes' }));
      await settle();
    }
    if (c.endsWhileOpen) {
      await act(async () => {
        await vi.advanceTimersByTimeAsync(11 * 60 * 1000);
      });
    }

    expect(container.innerHTML).toBe(TONIGHT[name]);
  });

  it('pins every case', () => {
    expect(Object.keys(TONIGHT).sort()).toEqual(Object.keys(tonightCases).sort());
  });
});
